---
- hosts: redhat-servers
  vars:
    nginx_user: nginx
  become: true
  become_method: sudo
  become_user: root
  remote_user: saa
  roles:
    - epel
    - nginx

- hosts: debian-servers
  vars:
    nginx_user: www-data
  become: true
  become_method: sudo
  become_user: root
  remote_user: saa
  roles:
    - nginx
